// Configuration file for network access
// This file is auto-generated by serve-local.sh or serve-network.sh
// Default configuration for local development
const CONFIG = {
    // Default to localhost
    SERVER_IP: 'localhost',
    BACKEND_PORT: 8000,
    
    // Get the full API URL
    getApiUrl: function() {
        return 'http://localhost:8000';
    }
};